{% set name = "pytest-flask-sqlalchemy" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db71a57b90435e5d854b21c37a2584056d6fc3ddb28c09d8d0a2546bd6e390ff

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_flask_sqlalchemy

about:
  home: https://github.com/jeancochrane/pytest-flask-sqlalchemy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pytest plugin for preserving test isolation in Flask-SQLAlchemy using database transactions.
  description: |
    pytest-flask-sqlalchemy is a simple pytest plugin for use with tests that need a databse conection, with it can
    acess the database to do the tests without problems with trash data and other problems that can be happened.
  doc_url: https://github.com/jeancochrane/pytest-flask-sqlalchemy
  dev_url: https://github.com/jeancochrane/pytest-flask-sqlalchemy

extra:
  recipe-maintainers:
    - csantosss
    - igortg
